#!/usr/bin/env python3

from collections import defaultdict

instructions = [line.split() for line in open("input")]

data = defaultdict(int)


for reg, ins, amount, _, other_reg, comp, val in instructions:
    comp = {"<": "__lt__", ">": "__gt__", ">=": "__ge__", "<=": "__le__", "==": "__eq__"}
    if getattr(int, comp)(data[other_reg], val):
        if ins == "inc":
            data[reg] += int(amount)
        else:
            data[reg] -= int(amount)

print(max(data.values()))

